---
title: "Histórico das aulas do curso"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE}
source("setup_knitr.R")
```

Abaixo o histórico de atividades realizadas em classe e atividades extra
classe aplicadas.


```{r, eval=FALSE, include=FALSE}
## Gera a lista com as datas de todas as aulas. O resultado do último
## comando pode ser copiado direto para o documento
datas.ter <- seq.Date(as.Date("2018-07-31"), as.Date("2018-11-27"),
                      by = "week")
datas.ter <- format.Date(datas.ter, format = "%d/%m")
datas.qui <- seq.Date(as.Date("2018-08-02"), as.Date("2018-11-29"),
                      by = "week")
datas.qui <- format.Date(datas.qui, format = "%d/%m")
cat(paste0("- **", datas.ter, "**:\n", "- **", datas.qui, "**:\n"))
cat(paste0("- **", datas.ter, " (Ter)", "**:\n", "- **",
           datas.qui, " (Qui)", "**:\n"))
```

- **31/07 (Ter)**:
- **02/08 (Qui)**:
- **07/08 (Ter)**:
- **09/08 (Qui)**:
- **14/08 (Ter)**:
- **16/08 (Qui)**:
- **21/08 (Ter)**:
- **23/08 (Qui)**:
- **28/08 (Ter)**:
- **30/08 (Qui)**:
- **04/09 (Ter)**:
- **06/09 (Qui)**:
- **11/09 (Ter)**:
- **13/09 (Qui)**:
- **18/09 (Ter)**:
- **20/09 (Qui)**:
- **25/09 (Ter)**:
- **27/09 (Qui)**:
- **02/10 (Ter)**:
- **04/10 (Qui)**:
- **09/10 (Ter)**:
- **11/10 (Qui)**:
- **16/10 (Ter)**:
- **18/10 (Qui)**:
- **23/10 (Ter)**:
- **25/10 (Qui)**:
- **30/10 (Ter)**:
- **01/11 (Qui)**:
- **06/11 (Ter)**:
- **08/11 (Qui)**:
- **13/11 (Ter)**:
- **15/11 (Qui)**:
- **20/11 (Ter)**:
- **22/11 (Qui)**:
- **27/11 (Ter)**:
- **29/11 (Qui)**:
