---
title: "Notas"
output:
  html_document:
    toc: false
    df_print: paged
---

```{r setup, include=FALSE}
source("setup_knitr.R")
```

```{r funcoes, include=FALSE}
## Função para calcular a média final, arredondando para CIMA.
## Ainda falta uma regra para decidir se notas como 68, 69, serão
## arredondadas para 70.
calc.media <- function(da, np){
    ## da: data.frame com as colunas de notas
    ## np: número de provas consideradas
    db <- t(apply(da, 1, sort, decreasing = TRUE, na.last = TRUE))
    db <- db[, 1:np]
    res <- ceiling(rowSums(db, na.rm = TRUE)/np)
    return(res)
}

## Função para definir a situação dos alunos:
## Se x >= 70 "Ap"
## Se 40 <= x < 70 "Ex"
## Se x < 40 "Re"
sit <- function(x){
    ## x: médias finais
    res <- rep("Ap", times = length(x))
    res[x >= 40 & x < 70] <- "Ex"
    res[x < 40] <- "Re"
    return(res)
}

```

```{r notas, eval=FALSE}
notas <- read.csv2('misc/notas-MB.csv')
notas <- notas[order(notas$Matrícula), ]
kable(notas, row.names = FALSE)
```
